project_name: ripfs
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: cmd/ripfs/main.go
    goos:
      - linux
      - darwin
#      - windows  # TODO
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: false

release:
  extra_files:
    - glob: ./offline/payload.tar.gz
      name_template: offline-payload.tar.gz
