name: publish

on:
  push:
    tags:
      - '*'

permissions:
  packages: write

jobs:
  tests:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: earthly/actions-setup@v1
        with:
          version: "latest" # or pin to an specific version, e.g. "v0.6.10"
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: earthly version
        run: earthly --version
      - name: build
        run: earthly --ci +publish --GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
